apiVersion: v1
kind: Secret
metadata:
  name: coursehub-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: change_me
  APPLICATION_SECURITY_JWT_SECRET_KEY: change_me_to_a_base64_encoded_secret

